In [1]:
import pandas as pd
import json
import requests

In [2]:
states = requests.get("https://api.livecovid.in/api/state")

stateparsed = json.loads(states.text)

In [3]:
df = pd.DataFrame(stateparsed["statewise"])

In [4]:
statename = []
for i in range(len(df.iloc[['1']].values[0])):
    statename.append(df.iloc[['1']].values[0][i])

In [5]:
activecases = []
for i in range(len(df.iloc[['2']].values[0])):
    activecases.append(df.iloc[['2']].values[0][i])

In [6]:
confirmedcases = []
for i in range(len(df.iloc[['3']].values[0])):
    confirmedcases.append(df.iloc[['3']].values[0][i])

In [7]:
deathcases = []
for i in range(len(df.iloc[['4']].values[0])):
    deathcases.append(df.iloc[['4']].values[0][i])

In [8]:
recovercases = []
for i in range(len(df.iloc[['6']].values[0])):
    recovercases.append(df.iloc[['6']].values[0][i])

In [9]:
dates = []
for i in range(len(df.iloc[['7']].values[0])):
    dates.append(df.iloc[['7']].values[0][i])

In [10]:
newData = pd.DataFrame()

In [11]:
newData["States"] = statename

In [12]:
newData["Active"] = activecases

In [13]:
newData["Confirmed"] = confirmedcases

In [14]:
newData["Deaths"] = deathcases

In [15]:
newData["Recovered"] = recovercases

In [16]:
newData["Date"] = dates

In [17]:
lat = {'Delhi':28.7041, 'Haryana':29.0588, 'Kerala':10.8505, 'Rajasthan':27.0238,
       'Telengana':18.1124, 'Uttar Pradesh':26.8467, 'Ladakh':34.2996, 'Tamil Nadu':11.1271,
       'Jammu and Kashmir':33.7782, 'Punjab':31.1471, 'Karnataka':15.3173, 'Maharashtra':19.7515,
       'Andhra Pradesh':15.9129, 'Odisha':20.9517, 'Uttarakhand':30.0668, 'West Bengal':22.9868, 
       'Puducherry': 11.9416, 'Chandigarh': 30.7333, 'Chhattisgarh':21.2787, 'Gujarat': 22.2587, 
       'Himachal Pradesh': 31.1048, 'Madhya Pradesh': 22.9734, 'Bihar': 25.0961, 'Manipur':24.6637, 
       'Mizoram':23.1645, 'Goa': 15.2993, 'Andaman and Nicobar Islands': 11.7401, 'Assam' : 26.2006, 
       'Jharkhand': 23.6102, 'Arunachal Pradesh': 28.2180, 'Tripura': 23.9408}

long = {'Delhi':77.1025, 'Haryana':76.0856, 'Kerala':76.2711, 'Rajasthan':74.2179,
        'Telengana':79.0193, 'Uttar Pradesh':80.9462, 'Ladakh':78.2932, 'Tamil Nadu':78.6569,
        'Jammu and Kashmir':76.5762, 'Punjab':75.3412, 'Karnataka':75.7139, 'Maharashtra':75.7139,
        'Andhra Pradesh':79.7400, 'Odisha':85.0985, 'Uttarakhand':79.0193, 'West Bengal':87.8550, 
        'Puducherry': 79.8083, 'Chandigarh': 76.7794, 'Chhattisgarh':81.8661, 'Gujarat': 71.1924, 
        'Himachal Pradesh': 77.1734, 'Madhya Pradesh': 78.6569, 'Bihar': 85.3131, 'Manipur':93.9063, 
        'Mizoram':92.9376, 'Goa': 74.1240, 'Andaman and Nicobar Islands': 92.6586, 'Assam' : 92.9376, 
        'Jharkhand': 85.2799, 'Arunachal Pradesh': 94.7278, 'Tripura': 91.9882}

newData['Latitude'] = newData['States'].map(lat)
newData['Longitude'] = newData['States'].map(long)

In [18]:
newData

,States,Active,Confirmed,Deaths,Recovered,Date,Latitude,Longitude
0,Maharashtra,1945,2334,160,229,2020-04-13T23:10:27+00:00,19.7515,75.7139
1,Delhi,1451,1510,28,31,2020-04-13T22:46:07+00:00,28.7041,77.1025
2,Tamil Nadu,1104,1173,11,58,2020-04-13T18:35:25+00:00,11.1271,78.6569
3,Rajasthan,813,945,11,121,2020-04-14T10:35:25+00:00,27.0238,74.2179
4,Madhya Pradesh,513,614,50,51,2020-04-13T20:20:25+00:00,22.9734,78.6569
5,Telangana,472,592,17,103,2020-04-13T22:01:06+00:00,NaN,NaN
6,Gujarat,536,617,26,55,2020-04-14T11:35:25+00:00,22.2587,71.1924
7,Uttar Pradesh,504,558,5,49,2020-04-13T21:38:02+00:00,26.8467,80.9462
8,Andhra Pradesh,420,439,7,12,2020-04-12T19:20:25+00:00,15.9129,79.7400
9,Kerala,178,378,2,198,2020-04-13T18:17:35+00:00,10.8505,76.2711
10,Jammu and Kashmir,250,270,4,16,2020-04-13T19:35:28+00:00,33.7782,76.5762
11,Karnataka,179,247,8,60,2020-04-13T22:46:15+00:00,15.3173,75.7139
12,Haryana,142,196,3,51,2020-04-13T18:40:26+00:00,29.0588,76.0856
13,West Bengal,147,190,7,36,2020-04-14T10:40:25+00:00,22.9868,87.8550
14,Punjab,139,176,12,25,2020-04-13T18:20:25+00:00,31.1471,75.3412
15,Bihar,37,66,1,28,2020-04-13T22:46:16+00:00,25.0961,85.3131
16,Odisha,37,56,1,18,2020-04-14T10:25:25+00:00,20.9517,85.0985
17,Uttarakhand,28,35,0,7,2020-04-08T21:20:26+00:00,30.0668,79.0193
18,Himachal Pradesh,18,32,2,12,2020-04-12T21:35:27+00:00,31.1048,77.1734
19,Chhattisgarh,21,31,0,10,2020-04-13T03:22:26+00:00,21.2787,81.8661
20,Assam,30,31,1,0,2020-04-14T10:00:26+00:00,26.2006,92.9376
21,Jharkhand,22,24,2,0,2020-04-13T20:50:25+00:00,23.6102,85.2799
22,Chandigarh,14,21,0,7,2020-04-10T18:10:27+00:00,30.7333,76.7794
23,Ladakh,5,17,0,12,2020-04-13T21:15:27+00:00,34.2996,78.2932
24,Andaman and Nicobar Islands,1,11,0,10,2020-03-30T11:27:27+00:00,11.7401,92.6586
25,Goa,2,7,0,5,2020-04-11T23:26:44+00:00,15.2993,74.1240
26,Puducherry,6,7,0,1,2020-04-10T17:50:26+00:00,11.9416,79.8083
27,Manipur,1,2,0,1,2020-04-06T22:35:54+00:00,24.6637,93.9063
28,Tripura,2,2,0,0,2020-04-10T20:00:27+00:00,23.9408,91.9882
29,Mizoram,1,1,0,0,2020-03-26T07:19:29+00:00,23.1645,92.9376
30,Arunachal Pradesh,1,1,0,0,2020-04-02T11:42:31+00:00,28.2180,94.7278
31,Dadra and Nagar Haveli,1,1,0,0,2020-04-06T15:22:25+00:00,NaN,NaN
32,Nagaland,1,1,0,0,2020-04-12T23:35:29+00:00,NaN,NaN
33,Meghalaya,1,1,0,0,2020-04-13T22:52:41+00:00,NaN,NaN
34,Daman and Diu,0,0,0,0,2020-03-26T07:19:29+00:00,NaN,NaN
35,Lakshadweep,0,0,0,0,2020-03-26T07:19:29+00:00,NaN,NaN
36,Sikkim,0,0,0,0,2020-03-26T07:19:29+00:00,NaN,NaN

In [19]:
newData.to_csv("covid_19_india.csv")